name: Build and Release YTSummary

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > skul9x.jks

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Prepare APK for Release
        run: |
          # Tìm file APK đã build
          apk_path=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          cp "$apk_path" YTSummary.apk
          cp "$apk_path" YTSummary-v1.0.7.apk

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          tag_name: Release v1.0.7
          name: Release v1.0.7
          draft: false
          prerelease: false
          files: |
            YTSummary.apk
            YTSummary-v1.0.7.apk
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
